language: cpp

compiler:
  - g++

install:
  - sudo add-apt-repository ppa:mhier/libboost-latest -y
  - sudo add-apt-repository ppa:octave/stable -y
  - sudo apt-get update -qq -y
  - sudo apt-get install octave octave-common liboctave4 liboctave-dev libhdf5-serial-dev libhdf5-dev libhdf5-10
  - sudo apt-get install -q libcppunit-dev libboost-all-dev cmake
  - if [[ "$CXX" == "g++" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update -qq -y;
      sudo apt-get install -q gcc-4.8 g++-4.8 libstdc++-4.8-dev;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100;
      sudo update-alternatives --config gcc;
      sudo update-alternatives --config g++;
      g++ --version;
    else
      clang --version;
    fi
  - git clone https://github.com/G-Node/nix.git nix-build
  - cd nix-build
  - cmake -DBUILD_TESTING=OFF .
  - make
  - sudo make install
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

notifications:
  irc: "chat.freenode.net#gnode"
